# Machine Learning Zoomcamp

## 1.7. Introduction to Numpy

In [2]:
import numpy as np
np

<module 'numpy' from '/usr/local/python/3.12.1/lib/python3.12/site-packages/numpy/__init__.py'>

### Creating an array

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 3.5)

array([3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5])

In [6]:
a = np.array([1,2,3,4,5,7,12,14])
a

array([ 1,  2,  3,  4,  5,  7, 12, 14])

In [7]:
a[2] = 10
a

array([ 1,  2, 10,  4,  5,  7, 12, 14])

In [8]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(2, 10, 3)

array([2, 5, 8])

In [10]:
np.linspace(1,2,12)

array([1.        , 1.09090909, 1.18181818, 1.27272727, 1.36363636,
       1.45454545, 1.54545455, 1.63636364, 1.72727273, 1.81818182,
       1.90909091, 2.        ])

### Multi-dimensional arrays

In [12]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [17]:
n[0]

array([1, 2, 3])

In [18]:
n[:,2]

array([3, 6, 9])

In [19]:
n[:,2] = [4,8,12]

In [20]:
n[:]

array([[ 1,  2,  4],
       [ 4,  5,  8],
       [ 7,  8, 12]])

### Arrays generated randomly

In [31]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [30]:
np.random.seed(2)
100 * np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [28]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [29]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

### Element-wise operations

In [33]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [34]:
a ** 2

array([ 0,  1,  4,  9, 16])

In [36]:
b = a**2 /2
b

array([0. , 0.5, 2. , 4.5, 8. ])

In [37]:
c = a + b
c

array([ 0. ,  1.5,  4. ,  7.5, 12. ])

### Comparison operations

In [39]:
a

array([0, 1, 2, 3, 4])

In [38]:
a  > 2

array([False, False, False,  True,  True])

In [40]:
b

array([0. , 0.5, 2. , 4.5, 8. ])

In [41]:
b > 2

array([False, False, False,  True,  True])

In [42]:
a > b 

array([False,  True, False, False, False])

In [43]:
a[a>b]

array([1])

### Summarizing operations

In [45]:
a

array([0, 1, 2, 3, 4])

In [49]:
# min, max, mean, std
a.max()

np.int64(4)