# 1.8. LINEAR ALGEBRA REFRESHER

## Vector operations

In [1]:
import numpy as np

In [4]:
u = np.array([2, 7, 5, 6])
v = np.array([3, 4, 8, 6])

In [7]:
# Addition
u + v

array([ 5, 11, 13, 12])

In [8]:
# Substraction
u - v

array([-1,  3, -3,  0])

In [9]:
# Scalar multiplication
2*v

array([ 6,  8, 16, 12])

## Multiplication

### Vector-vector multiplication

In [14]:
def vector_vector_multiplication(u,v):
    # verify the shape before operation
    assert u.shape[0] == v.shape[0]
    n = u.shape[0]

    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]

    return result

In [15]:
vector_vector_multiplication(u,v)

np.float64(110.0)

In [21]:
u.dot(v)

np.int64(110)

### Matrix-vector multiplication

In [18]:
U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [19]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

In [20]:
matrix_vector_multiplication(U, v)

array([98., 31., 35.])

In [22]:
U.dot(v)

array([98, 31, 35])

### Matrix-matrix multiplication

In [27]:
V = np.array([
    [1,1,2],
    [0,0.5,1],
    [0,2,1],
    [2,1,0],
])
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [28]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [29]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [30]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

### Identity Matrix

In [34]:
# It's like 1           x*1=x
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [36]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

### Matrix Inverse

In [37]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
])
inv = np.linalg.inv(V)

In [38]:
inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])